apiVersion: v2
name: ctfd
description: A Helm chart to deploy CTFd on Kubernetes. HA/Autoscaling + MariaDB + Redis + SeaweedFS S3
icon: https://ctfd.io/static/img/ctfd.svg

type: application

version: 0.2.0

# Redis, MySQL/MariaDB and Seaweedfs
dependencies:
  - name: redis
    version: 20.0.5
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: mariadb
    version: 19.0.5
    repository: https://charts.bitnami.com/bitnami
    condition: mariadb.enabled
  - name: seaweedfs
    version: 4.0.0
    repository: https://seaweedfs.github.io/seaweedfs/helm
    condition: seaweedfs.enabled
