apiVersion: v2
name: ctfd
description: A Helm chart to deploy CTFd on Kubernetes. HA/Autoscaling + MariaDB + Redis + MinIO
icon: https://ctfd.io/static/img/ctfd.svg

type: application

# Dev note: trigger a helm chart release by bumping the version
version: 0.3.0

# Redis, MySQL/MariaDB and MinIO
dependencies:
  - name: redis
    version: 20.0.5
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: mariadb-galera
    version: 14.0.12
    repository: https://charts.bitnami.com/bitnami
    condition: mariadb-galera.enabled
  - name: minio
    alias: minio
    version: 5.4.0
    repository: https://charts.min.io/
    condition: minio.enabled
