{{- if .Values.seaweedfs.enabled }}
{{- $access_key_admin := randAlphaNum 16 -}}
{{- $secret_key_admin := randAlphaNum 32 -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Values.seaweedfs.s3.existingConfigSecret }}
stringData:
  admin_access_key_id: {{ $access_key_admin }}
  admin_secret_access_key: {{ $secret_key_admin }}
  seaweedfs_s3_config: '{"identities":[{"name":"anvAdmin","credentials":[{"accessKey":"{{ $access_key_admin }}","secretKey":"{{ $secret_key_admin }}"}],"actions":["Admin","Read","Write"]},{"name":"anonymous","actions":["Read"]}]}'
{{- end }}
