apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ctfd.fullname" . }}
type: Opaque
data:
  SECRET_KEY: {{ include "ctfd.SECRET_KEY" . | b64enc }}
  DATABASE_URL: {{ include "ctfd.DATABASE_URL" . | b64enc }}
  REDIS_URL: {{ include "ctfd.REDIS_URL" . | b64enc }}
  {{- if .Values.ctfd.uploadprovider.s3.enabled }}
  AWS_ACCESS_KEY_ID: {{ .Values.ctfd.uploadprovider.s3.access_key_id | b64enc }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.ctfd.uploadprovider.s3.secret_access_key | b64enc }}
  AWS_S3_BUCKET: {{ .Values.ctfd.uploadprovider.s3.bucket | b64enc }}
  AWS_S3_ENDPOINT_URL: {{ .Values.ctfd.uploadprovider.s3.endpoint_url | b64enc }}
  {{- end }}
