{{- if .Values.ctfd.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ctfd.serviceAccountName" . }}
  labels:
    {{- include "ctfd.labels" . | nindent 4 }}
  {{- with .Values.ctfd.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.ctfd.serviceAccount.automount }}
{{- end }}
