name: "Publish Helm Chart"
on: 
  push:
    branches:
      - main
    paths:
      - 'templates/**'
      - 'values.yaml'
      - 'Chart.yaml'

permissions:
  contents: write
  pages: write

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v4
          
      - name: add helm repos
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo add minio https://charts.min.io
          helm repo update
          helm dep up

      - name: Run chart-releaser
        run: |
          wget -O /tmp/chart-releaser_1.6.1_linux_amd64.tar.gz https://github.com/helm/chart-releaser/releases/download/v1.6.1/chart-releaser_1.6.1_linux_amd64.tar.gz
          tar -zxvf /tmp/chart-releaser_1.6.1_linux_amd64.tar.gz -C /tmp
          /tmp/cr package .
          /tmp/cr upload --owner ${{ github.repository_owner }} --git-repo ${{ github.repository }} --packages-with-index --token ${{ secrets.GITHUB_TOKEN }} --push --skip-existing
          /tmp/cr index --owner ${{ github.repository_owner }}  --git-repo ${{ github.repository }}  --packages-with-index --index-path . --token ${{ secrets.GITHUB_TOKEN }} --push